export const USAStates = [
    {
      name: 'Alabama',
      id: 'US-AL',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'Alaska',
      id: 'US-AK',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'American Samoa',
      id: 'US-AS',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'Arizona',
      id: 'US-AZ',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'Arkansas',
      id: 'US-AR',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'California',
      id: 'US-CA',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'Colorado',
      id: 'US-CO',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'Connecticut',
      id: 'US-CT',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'Delaware',
      id: 'US-DE',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'Federated States Of Micronesia',
      id: 'US-FM',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'Florida',
      id: 'US-FL',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'Georgia',
      id: 'US-GA',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'Guam',
      id: 'US-GU',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'Hawaii',
      id: 'US-HI',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'Idaho',
      id: 'US-ID',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'Illinois',
      id: 'US-IL',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'Indiana',
      id: 'US-IN',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'Iowa',
      id: 'US-IA',
    },
    {
      name: 'Kansas',
      id: 'US-KS',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'Kentucky',
      id: 'US-KY',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'Louisiana',
      id: 'US-LA',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'Maine',
      id: 'US-ME',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'Marshall Islands',
      id: 'US-MH',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'Maryland',
      id: 'US-MD',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'Massachusetts',
      id: 'US-MA',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'Michigan',
      id: 'US-MI',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'Minnesota',
      id: 'US-MN',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'Mississippi',
      id: 'US-MS',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'Missouri',
      id: 'US-MO',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'Montana',
      id: 'US-MT',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'Nebraska',
      id: 'US-NE',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'Nevada',
      id: 'US-NV',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'New Hampshire',
      id: 'US-NH',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'New Jersey',
      id: 'US-NJ',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'New Mexico',
      id: 'US-NM',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'New York',
      id: 'US-NY',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'North Carolina',
      id: 'US-NC',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'North Dakota',
      id: 'US-ND',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'Northern Mariana Islands',
      id: 'US-MP',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'Ohio',
      id: 'US-OH',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'Oklahoma',
      id: 'US-OK',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'Oregon',
      id: 'US-OR',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'Palau',
      id: 'US-PW',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'Pennsylvania',
      id: 'US-PA',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'Puerto Rico',
      id: 'US-PR',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'Rhode Island',
      id: 'US-RI',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'South Carolina',
      id: 'US-SC',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'South Dakota',
      id: 'US-SD',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'Tennessee',
      id: 'US-TN',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'Texas',
      id: 'US-TX',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'Utah',
      id: 'US-UT',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'Vermont',
      id: 'US-VT',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'Virgin Islands',
      id: 'US-VI',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'Virginia',
      id: 'US-VA',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'Washington',
      id: 'US-WA',
    },
    {
      name: 'West Virginia',
      id: 'US-WV',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'Wisconsin',
      id: 'US-WI',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
    {
      name: 'Wyoming',
      id: 'US-WY',
      value: 0,
      active: 0,
      deaths: 0,
      recovered: 0,
    },
  ];